### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by Bayonetta** [keith/reminders-cli#1]
After install reminders, I test 'reminders show-lists', but terminal outputs like that.

```shell
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/bin/reminders
  Reason: image not found
[1]    96728 trace trap  reminders
```

**Comment by neonichu** [comment]
Yah, the binary links against Swift dylibs for a snapshot, so the `@rpath` is specific to having that installed. I would recommend just building from source as the easiest method. Alternatively, you can install the `DEVELOPMENT-SNAPSHOT-2016-02-08-a` from swift.org.

**Comment by keith** [comment]
Fixed with a new release! https://github.com/keith/reminders-cli/releases/tag/1.0.2

Thanks guys!
