### ISSUE TITLE
Reminders 7.0 (2079) List Order Not Preserved

### ISSUE THREAD

**Issue by GordonMcKinney** [keith/reminders-cli#10]
This is a great program, thank you!

I noticed my CLI list-items are not appearing in the same order as the Reminders app.

I'm a software engineer, I can assist if you can give me a hint on where to focus my attention.

**Comment by keith** [comment]
Have you changed how they are ordered in the app at all? It looks like right now I'm just ordering by creation date https://github.com/keith/reminders-cli/blob/869192d71c59e471b37e996c9002cc722d9ad1d8/Sources/Reminders.swift#L85

which I assume means if you've dragged them it will no longer match. I bet there's some way to do that correctly tho

**Comment by GordonMcKinney** [comment]
PR #11
