### ISSUE TITLE
[Feature Request] Add reminder notification time

### ISSUE THREAD

**Issue by theboyler** [keith/reminders-cli#32]
I'm loving this - thanks to all who have worked on it!

It would be great if in addition to adding the due date and time, you could also add a time for the reminder, using syntax like this to add a reminder time to be 5 minutes before the date/time:

reminders add Today Remember the milk -d "today 10am" -5

**Comment by theboyler** [comment]
Further to this, I see now that the due date is the notification time,  but this doesn't seem to trigger in Big Sur Reminders, so a remind me time passes without a notification :(

**Comment by keith** [comment]
This CLI just directly adds reminders straight to Reminders.app, so any notifications you have that configured to do should work just as if you added them in the app. But yes as you noted the due date is the reminder time, it doesn't appear to me that reminders has a separate field for this, so they have to match
