### ISSUE TITLE
[Feature Request] Add a note from the command line

### ISSUE THREAD

**Issue by munkee** [keith/reminders-cli#54]
Maybe I've missed it in the documentation, but it'd be nice to have something like
`reminders add Grocery "Canned Tomatoes" --note "14.5 oz can, Diced"`
to end up with something like this:
<img width="352" alt="Screenshot 2023-01-09 at 8 43 04 AM" src="https://user-images.githubusercontent.com/104308/211334595-c3b823d1-2940-412b-99be-223dbf88c3cc.png">

Probably there's a better way to make it easy to type then what I just came up with.
Maybe when you add it should return the <index> to you and you could just:
`>reminders add Grocery Canned Tomatoes`
`<Added 'Canned Tomatoes' to 'Grocery' (10)`
`>reminders note Grocery 10 14.5 oz can, Diced`

**Comment by keith** [comment]
https://github.com/keith/reminders-cli/pull/56

**Comment by keith** [comment]
released in 2.1.1
