### ISSUE TITLE
Feature Request - editing a "completed" item and changing status back to "incomplete" again

### ISSUE THREAD

**Issue by caltuntas** [keith/reminders-cli#63]
I have started using this utility yesterday. I'm trying to make it part of my current work flow. As far as I can see, we can edit an item text/description. Today I accidentally completed an item and wanted to edit and change the status back to "incomplete" again but couldn't see that option. I would be a good option to have as a feature. Thanks.

**Comment by keith** [comment]
Make sense, I think probably what we'd want would be `reminders uncomplete` (or some other word) command, PRs welcome!

**Comment by caltuntas** [comment]
I have submitted the PR #64 for this feature request.

**Comment by keith** [comment]
thanks! released in 2.3.0
