### ISSUE TITLE
cannot notice me

### ISSUE THREAD

**Issue by caton-hpg** [keith/reminders-cli#67]
I add a reminder with time. But It didn't notice me when the time came.

**Comment by keith** [comment]
you'll have to look at the reminder details in Reminders.app and make sure it looks correct. if it does check your Reminders.app notification settings.

**Comment by caton-hpg** [comment]
![image](https://github.com/keith/reminders-cli/assets/87342612/ffc990b2-8155-4f69-adaa-48ee6a3f5ef0)

`hello 003` create by cmd `reminders add test hello 003 --due-date "2023-09-01 12:13" --notes '早地铁'`.
`hello 004` create by mac app.

`hello 004` can notice to me in iphone and mac. `hello 003` cannot.

**Comment by keith** [comment]
fixed in https://github.com/keith/reminders-cli/releases/tag/2.5.0
