### ISSUE TITLE
Notification doesn't work

### ISSUE THREAD

**Issue by thdonatello** [keith/reminders-cli#76]
Hi! Thx you for your app!

I can set up reminder, I see it in GUI on all my devices.
But notofocation (sound/banner/alert) doesn't work. They are not in notification center, watch doesn't have reaction.
Remind's time becomes red in reminders app.

If I set up remind with app I have notification.
MacOS Sonoma 14.3.1
reminders-cli 2.4.0

**Comment by keith** [comment]
fixed in https://github.com/keith/reminders-cli/releases/tag/2.5.0

**Comment by thdonatello** [comment]
I have:

```
# brew install keith/formulae/reminders-cli
==> Fetching keith/formulae/reminders-cli
==> Downloading https://github.com/keith/reminders-cli/releases/download/2.5.0/reminders.tar.gz
curl: (22) The requested URL returned error: 404

Error: reminders-cli: Failed to download resource "reminders-cli"
Download failed: https://github.com/keith/reminders-cli/releases/download/2.5.0/reminders.tar.gz
```
😕
