### ISSUE TITLE
Build artifact missing from 2.5.0 release

### ISSUE THREAD

**Issue by cadeef** [keith/reminders-cli#78]
The build artifact (reminders.tar.gz) is missing from the 2.5.0 release which causes Homebrew upgrade/install to fail:

```
==> Upgrading 1 outdated package:
keith/formulae/reminders-cli 2.4.0 -> 2.5.0
==> Fetching keith/formulae/reminders-cli
==> Downloading https://github.com/keith/reminders-cli/releases/download/2.5.0/reminders.tar.gz
curl: (22) The requested URL returned error: 404

Error: reminders-cli: Failed to download resource "reminders-cli"
Download failed: https://github.com/keith/reminders-cli/releases/download/2.5.0/reminders.tar.gz
```
[Only source code archives are listed as available assets.](https://github.com/keith/reminders-cli/releases/tag/2.5.0)

**Comment by keith** [comment]
Ooops, thanks, fixed! (you have to make sure brew updates the formula because the sha changed, AFAIUI it does this by default unless you opt out)
