### ISSUE TITLE
Open for potential API changes?

### ISSUE THREAD

**Issue by marbetschar** [keith/reminders-cli#8]
Hi Keith!

The idea of having a CLI interface to Apple Reminders is awesome! I'm going to need this in my next side project, where I'm going to build some Charts based upon the data lying within Reminders.

**TL;DR**
Are you open for pull requests containing non-backwards-compatible API changes for `reminders-cli` or should I fork the repo and go on from there?

**The long story**
For my side project I'm especially interested in meta information such as `isCompleted`, `dueDateComponents` and `completionDate`. In addition, I'll also need some sort of querying possibility, and a way to define the output format to make it easily parseable by the Charting part of my app (some sort of `--format json` flag will do). Since `reminders-cli` as of now is fairly basic, I expect I'll have to make some big changes, which may result in a new, non-backwards-compatible API. Is that fine with you?

**Comment by keith** [comment]
I'm definitely open to breaking changes but I would like to generally keep the simplicity of how this tool works now. I wouldn't want to make the simple things hard to do.
