### ISSUE TITLE
Question: Working on Alfred Workfow companion

### ISSUE THREAD

**Issue by whazlewo** [keith/reminders-cli#80]
I'm thinking about how I could build an Alfred app workflow using your CLI. I love that you have a json format option, but I'm trying to figure out how you do the indexing in the terminal output. Is it safe to assume the ordering of the output is always the same (ie that the first result in the json output is "0")? 

is it safe for me to always assume that ...
```
0: task 1
1: task 2
2: task 3
```
matches up exactly with the order of the json array when using `--format json`?

```
[
    { "title": "task 1" },
    { "title": "task 2" ),
    { "title": "task 3" )
]
```

**Comment by keith** [comment]
you should probably rely on this instead https://github.com/keith/reminders-cli/pull/55

**Comment by whazlewo** [comment]
Oh!! You can pass the externalId OR the array index as a parameter for completing, editing, and deleting items??  That is very cool.
