### ISSUE TITLE
Is `export-all` merged?

### ISSUE THREAD

**Issue by uwo** [keith/reminders-cli#83]
Forgive my confusion -- using the most recent version, 2.5.1, I cannot seem to find the `export-all` command, nor do I see its corresponding source code when grep'ing main. Was it decided not to include this feature?  (Apologies if I should have been able to figure this out on my own.)

**Comment by keith** [comment]
it's part of the show command instead. see `reminders show --help` for the formatting options https://github.com/keith/reminders-cli/pull/55
